### PR TITLE
reverted to python3.6 (gpnb 19.07.1)

### PR DESCRIPTION
**Pull request by alex-wenzel**
This pull request makes the notebook (with new visualizations from the F1000 revision) compatible with the `python3.6` kernel on the notebook server. Development was with the recommended stable version of the notebook server `19.07.1`. The notebook runs all the way through on the example dataset in the `19.07.1` docker container on my laptop.

### CODE REVIEW

**Comment by edjuaro** [comment]
I am running it locally and when I run it on the 3.6 kernel I get an error on the PCA step. 3.7 kernel runs just fine. I'm not sure how to proceed.

**Comment by alex-wenzel** [comment]
@edjuaro Can you confirm you're looking at the `36kernel` branch? That line of code should indeed cause a `KeyError` in the 3.6, but I have it commented out on the `36kernel` branch. 

image

**Comment by edjuaro** [comment]
Nope, I was on the develop branch -- my bad, that's the default branch I checkout for PRs. I'll check out the 36kernel branch.

**Comment by edjuaro** [comment]
It runs as expected. Note that I removed one line that seemed like a debugging line to me. See commit [53daea0](https://github.com/genepattern/single_cell_clustering_notebook/pull/23/commits/53daea00dd9b0542e171377328e460a044370679) for "details"

**Comment by edjuaro** [comment]
Should we clean up the many branches in this repo? I like the minimalist approach of "Only a master and a develop branch unless we *need* other branches"

**Comment by alex-wenzel** [comment]
@edjuaro Agreed. I'll go ahead and delete this branch. I'm sure the other ones can be deleted as well since they're quite old. Sorry also for the name confusion.

**Pull request merged**
